stages:
  - test

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

test_python34:
  stage: test
  script:
    - rm docker-compose.override.yml
    - docker-compose pull
    - docker-compose build --pull
    - docker-compose run --rm test tox --skip-missing-interpreters

test_python35:
  stage: test
  script:
    - rm docker-compose.override.yml
    - docker-compose pull
    - docker-compose build --pull
    - docker-compose run --rm test tox --skip-missing-interpreters

test_python36:
  stage: test
  script:
    - rm docker-compose.override.yml
    - docker-compose pull
    - docker-compose build --pull
    - docker-compose run --rm test tox --skip-missing-interpreters
