version: '2'
services:

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: vaulthelpers
      POSTGRES_PASSWORD: supersecretpassword

  vault:
    image: vault:latest
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: my-root-token

  test:
    build: .
    command: python sandbox/manage.py check
    depends_on:
      - postgres
      - vault
    environment:
      VAULT_TOKEN: my-root-token
      VAULT_URL: http://vault:8200/
      VAULT_CACERT:
      VAULT_SKIP_VERIFY: 'yes'
      VAULT_DEBUG: 'no'
      VAULT_DATABASE_PATH: database/creds/vaulthelpers-sandbox
      VAULT_AWS_PATH: aws/sts/vaulthelpers-sandbox
      DATABASE_URL: postgres://postgres:5432/vaulthelpers
      DATABASE_OWNERROLE: vaulthelpers
    volumes:
      - .:/code
